#!/usr/bin/env python3

# Copyright © 2020, Brendon Matheson
#
# This work is offered to you under the terms of the GNU GPL v2 license.  See 
# the file LICENSE for details.

import boto3
import os

print("doshutdown")

boto3.setup_default_session(profile_name="control-notification-service@prod")
client = boto3.client("sns")

client.publish(
    TopicArn="arn:aws:sns:<your-region>:<your-account-number>:control-notification",
    Message="Performing host shutdown",
    Subject="Performing host shutdown")

os.system("ssh shutdownbot@somenode1 \"sudo /sbin/shutdown -h now\" &")

os.system("ssh shutdownbot@somenode2 \"sudo /sbin/shutdown -h now\" &")

