# Copyright © 2020, Brendon Matheson
#
# This work is offered to you under the terms of the GNU GPL v2 license.  See
# the file LICENSE for details.

AWSTemplateFormatVersion: "2010-09-09"

Description: "control-notification"

Parameters:
  ProductName:
    Type: "String"
    Default: "control" 
  ModuleName:
    Type: "String"
    Default: "notification" 

Resources:

  NotificationTopic:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: !Sub "${ProductName}-${ModuleName}"
      Subscription: 
        - Protocol: "email"
          Endpoint: "you@your-amazing-and-lovely-domain-name.com"
        - Protocol: "sms"
          Endpoint: "+1234567890"
      Tags: 
        - Key: "product"
          Value: !Ref "ProductName"
        - Key: "module"
          Value: !Ref "ModuleName"
      TopicName: !Sub "${ProductName}-${ModuleName}"

  NotificationTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    DependsOn:
      - "NotificationTopic"
      - "ServiceUser"
    Properties: 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "Default"
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action:
              - "sns:GetTopicAttributes"
              - "sns:SetTopicAttributes"
              - "sns:AddPermission"
              - "sns:RemovePermission"
              - "sns:DeleteTopic"
              - "sns:Subscribe"
              - "sns:ListSubscriptionsByTopic"
              - "sns:Publish"
              - "sns:Receive"
            Resource: !Ref "NotificationTopic"
            Condition:
              StringEquals:
                "AWS:SourceOwner": !Sub "${AWS::AccountId}"
          - Sid: "AllowServiceUser"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/${ProductName}-${ModuleName}-service"
            Action:
              - "sns:publish"
            Resource: !Ref "NotificationTopic"
      Topics: 
        - !Ref "NotificationTopic"

  ServiceUser:
    Type: "AWS::IAM::User"
    Properties: 
      Tags: 
        - Key: "product"
          Value: !Ref "ProductName"
        - Key: "module"
          Value: !Ref "ModuleName"
      UserName: !Sub "${ProductName}-${ModuleName}-service"

